apiVersion: "kafka.strimzi.io/v1beta2"
kind: "KafkaConnector"
metadata:
  # connector name
  name: "sink-dimpromotion-ysql-05b34d19"
  labels:
    # kafka connect [cluster] name
    strimzi.io/cluster: edh
spec:
  class: io.confluent.connect.jdbc.JdbcSinkConnector
  tasksMax: 2
  config:
    key.converter: "io.confluent.connect.avro.AvroConverter"
    key.converter.schema.registry.url: "http://schema-registry-cp-schema-registry:8081"
    value.converter: "io.confluent.connect.avro.AvroConverter"
    value.converter.schema.registry.url: "http://schema-registry-cp-schema-registry:8081"
    connection.url: "jdbc:postgresql://yb-tservers.database.svc.cluster.local:5433/salesdw?user=plumber&password=PlumberSDE"
    connection.attempts: "2"
    topics: "dimpromotion_spark_stream_dwfiles"
    table.name.format: "public.dimpromotion"
    auto.create: "true"
    auto.evolve: "true"
    insert.mode: "upsert"
    pk.mode: "record_key"
    pk.fields: "PromotionKey"
    batch.size: "1500"
    delete.enabled: true